name       : nfoview
version    : 1.23
release    : 2
source     :
    - https://github.com/otsaloma/nfoview/archive/1.23.tar.gz : 7a3f07a363e4ff1df9bf67228092fb681db1889311387b7734654ab48af2e8f7
license    : GPL-3.0
component  : multimedia.graphics
summary    : NFO Viewer is a simple viewer for NFO files
description: |
    NFO Viewer is a simple viewer for NFO files, which are "ASCII" art in the CP437 codepage. The advantages of using NFO Viewer instead of a text editor are preset font and encoding settings, automatic window size and clickable hyperlinks.
builddeps  :
    - pkgconfig(python3)
rundeps    :
    - libgtk-3
    - python3-gobject
build      : |
    %python3_setup
install    : |
    %python3_install
