name       : nfoview
version    : '1.29'
release    : 10
source     :
    - https://github.com/otsaloma/nfoview/archive/refs/tags/1.29.tar.gz : 1aa8b067fc559fcd04c083b25c1a447f63143aa5ca9378cf4d8a1b5e4e5d62a3
homepage   : https://otsaloma.io/nfoview/
license    : GPL-3.0-or-later
component  : multimedia.graphics
summary    : NFO Viewer is a simple viewer for NFO files
description: |
    NFO Viewer is a simple viewer for NFO files, which are "ASCII" art in the CP437 codepage. The advantages of using NFO Viewer instead of a text editor are preset font and encoding settings, automatic window size and clickable hyperlinks.
builddeps  :
    - pkgconfig(python3)
rundeps    :
    - python-gobject
build      : |
    %make
install    : |
    %make_install PREFIX=/usr/
