name       : nfoview
version    : '1.28'
release    : 5
source     :
    - https://github.com/otsaloma/nfoview/archive/1.28.tar.gz : edf6b3cd15a50739779c9ac6249af10331558dd085662336d51641842abb7d3e
homepage   : https://otsaloma.io/nfoview/
license    : GPL-3.0-or-later
component  : multimedia.graphics
summary    : NFO Viewer is a simple viewer for NFO files
description: |
    NFO Viewer is a simple viewer for NFO files, which are "ASCII" art in the CP437 codepage. The advantages of using NFO Viewer instead of a text editor are preset font and encoding settings, automatic window size and clickable hyperlinks.
builddeps  :
    - pkgconfig(python3)
rundeps    :
    - python3-gobject
build      : |
    %python3_setup
install    : |
    %python3_install
